name: SA SMS WORK Bot

on:
  workflow_dispatch:  # শুধু manually চালাবে, push এ না

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo "ADMIN_ID=${{ secrets.ADMIN_ID }}" >> .env
          echo "LAMIX_URL=${{ secrets.LAMIX_URL }}" >> .env
          echo "LAMIX_USERNAME=${{ secrets.LAMIX_USERNAME }}" >> .env
          echo "LAMIX_PASSWORD=${{ secrets.LAMIX_PASSWORD }}" >> .env

      - name: Run bot
        run: python bot.py
